name: TraderHub CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        docker-compose version

    - name: Set Execute Permissions
      run: chmod +x docker-run.sh

    - name: Build Docker Image
      run: ./docker-run.sh build

    - name: Run Server and Basic Tests
      run: |
        # Start the server in background
        ./docker-run.sh server &
        
        # Wait for server to be ready
        sleep 10
        
        # Run some basic client commands to verify functionality
        ./docker-run.sh client view
        ./docker-run.sh client submit test_order1 trader1 AAPL 150.50 100 buy
        ./docker-run.sh client view AAPL
        ./docker-run.sh client cancel test_order1 buy

    - name: Clean Up Docker Resources
      if: always()
      run: ./docker-run.sh clean
